src/objects/RecentItemFilter__c.object
<CustomObject>
    <description>A object holds all users&apos; personal recent items filter settings. One user only has one record in this object.</description>
    <fields>
        <fullName>No_Of_Displayed_Items__c</fullName>
        <inlineHelpText>Define how many recent items you want to see. Maximum 200 records. Leave it blank if you want to see maximum records (200).</inlineHelpText>
        <label>No. Of Displayed Items</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Objects_List__c</fullName>
        <description>The list holds all object names available for user to select. Misspelling the name will stop the object record displaying. Please make sure you have correctly spell the object name by using the &quot;Label&quot; field of the object.</description>
        <inlineHelpText>Define what object you want to see ONLY. If you can not see the object you want, please contact your salesforce administrator.</inlineHelpText>
        <label>Objects List</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attachment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity: Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CaseComment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>RecentItemFilter</label>
    <nameField>
        <displayFormat>Filter-{0000}</displayFormat>
        <label>RecentItemFilter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RecentItemFilters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestRecentItemsFilter.cls
@isTest
private class TestRecentItemsFilter {
    
   
    static testMethod void NoID(){
             PageReference pageRef = new PageReference('Page.RecentItemsFilter');
            Test.setCurrentPage(pageRef);
            
            list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        delete filters;
			
			Integer counter=[select count() from RecentItemFilter__c];
			System.assertEquals(counter,0);
			
             test.startTest();

                RecentItemsFilter afilter=new RecentItemsFilter();
                afilter.save();
   
             test.stopTest();
     }
        
     static testMethod void Cover39(){
             PageReference pageRef = new PageReference('Page.RecentItemsFilter');
            Test.setCurrentPage(pageRef);
            
            list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        delete filters;

            test.startTest();
              RecentItemFilter__c myFilter=new RecentItemFilter__c(Objects_List__c='Account', No_Of_Displayed_Items__c=20);
             insert myFilter;

             RecentItemsFilter afilter2=new RecentItemsFilter();

            test.stopTest();
     }
        
    static testMethod void withid(){
             PageReference pageRef = new PageReference('Page.RecentItemsFilter');
            Test.setCurrentPage(pageRef);
            
            list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        delete filters;
            
            RecentItemFilter__c myFilter=new RecentItemFilter__c(Objects_List__c='Account', No_Of_Displayed_Items__c=20);
             insert myFilter;
                
            ApexPages.currentPage().getParameters().put('ID', myFilter.id);

             test.startTest();

                RecentItemsFilter afilter2=new RecentItemsFilter();

             test.stopTest();
   }
}