src/objects/RecentItemFilter__c.object
<CustomObject>
    <description>A object holds all users&apos; personal recent items filter settings. One user only has one record in this object.</description>
    <fields>
        <fullName>No_Of_Displayed_Items__c</fullName>
        <inlineHelpText>Define how many recent items you want to see. Maximum 200 records. Leave it blank if you want to see maximum records (200).</inlineHelpText>
        <label>No. Of Displayed Items</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Objects_List__c</fullName>
        <description>The list holds all object names available for user to select. Misspelling the name will stop the object record displaying. Please make sure you have correctly spell the object name by using the &quot;Label&quot; field of the object.</description>
        <inlineHelpText>Define what object you want to see ONLY. If you can not see the object you want, please contact your salesforce administrator.</inlineHelpText>
        <label>Objects List</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attachment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity: Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CaseComment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>RecentItemFilter</label>
    <nameField>
        <displayFormat>Filter-{0000}</displayFormat>
        <label>RecentItemFilter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RecentItemFilters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RecentItemsFilter.cls
public with sharing class RecentItemsFilter {
    
    public string mode {get;set;}    
    public RecentItemFilter__c anitem {get; private set;}
    
    //public RecentItemFilter__c getanitem() {
	   //return anitem;
	//}
	    
    public RecentItemsFilter(){

        
        if(ApexPages.currentPage().getParameters().get('id')<>null){
        	//update
        	     Id id = ApexPages.currentPage().getParameters().get('id');
        	     Integer mycounter=[select count() from RecentItemFilter__c where CreatedById=:userinfo.getUserId() and id=:id];
                 
                 if(mycounter==1){
                        anitem = (id == null) ? new RecentItemFilter__c() : [select id,Objects_List__c,CreatedById,No_Of_Displayed_Items__c from RecentItemFilter__c where CreatedById=:userinfo.getUserId()];
                        mode='enable';
                 }
                 else{
                 //there is id, but it either does not exist or belongs to someone else
                  mode='disable';
                 
                 }   

        }
        
        //create new
        else {
        	Integer mycounter=[select count() from RecentItemFilter__c where CreatedById=:userinfo.getUserId() ];
        	if(mycounter==0){
        		     String id = '';
        	        anitem = (id.length() ==0 ) ? new RecentItemFilter__c() : [select id,Objects_List__c,CreatedById,No_Of_Displayed_Items__c from RecentItemFilter__c where id=:id];
                    mode='enable';
        	}
        	else{
        	   mode='disable';
        	}

        }
        
        
        

    }
    
    
    public PageReference save(){
        //Integer mycounter=[select count() from RecentItemFilter__c where CreatedById=:userinfo.getUserId()];
        //if(mycounter==0){
            //RecentItemFilter__c anitem=new RecentItemFilter__c(Objects_List__c=)
            //insert anitem;
        //}
        //else{
            //update anitem;
        //}
        try {
		  upsert(anitem);
		} catch(System.DMLException e) {
		  ApexPages.addMessages(e);
		  return null;
		}
		        
        return null;
    }
    
    
    
}