src/objects/RecentItem__c.object
<CustomObject>
    <description>A object holds all users&apos; recent item records.</description>
    <fields>
        <fullName>Link__c</fullName>
        <inlineHelpText>The original record link. That&apos;s it, the URL in user&apos;s browser.</inlineHelpText>
        <label>Link</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>No_Of_Access__c</fullName>
        <inlineHelpText>How many times a user has accessed this record.</inlineHelpText>
        <label>No. Of Access</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <inlineHelpText>The object record belongs to.</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordID__c</fullName>
        <inlineHelpText>The 15 or 18 digits long salesforce record ID.</inlineHelpText>
        <label>RecordID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Name__c</fullName>
        <inlineHelpText>The name/subject/title of the record.</inlineHelpText>
        <label>Record Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <inlineHelpText>The user who accessed the record.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RecentItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RecentItem</label>
    <nameField>
        <displayFormat>Item-{0000}</displayFormat>
        <label>RecentItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RecentItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RecentItemFilter__c.object
<CustomObject>
    <description>A object holds all users&apos; personal recent items filter settings. One user only has one record in this object.</description>
    <fields>
        <fullName>No_Of_Displayed_Items__c</fullName>
        <inlineHelpText>Define how many recent items you want to see. Maximum 200 records. Leave it blank if you want to see maximum records (200).</inlineHelpText>
        <label>No. Of Displayed Items</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Objects_List__c</fullName>
        <description>The list holds all object names available for user to select. Misspelling the name will stop the object record displaying. Please make sure you have correctly spell the object name by using the &quot;Label&quot; field of the object.</description>
        <inlineHelpText>Define what object you want to see ONLY. If you can not see the object you want, please contact your salesforce administrator.</inlineHelpText>
        <label>Objects List</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attachment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity: Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CaseComment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>RecentItemFilter</label>
    <nameField>
        <displayFormat>Filter-{0000}</displayFormat>
        <label>RecentItemFilter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RecentItemFilters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestRecentItem.cls
@isTest
private class TestRecentItem {

	static testMethod void TestRecentItemExistingItem(){
	         PageReference pageRef = new PageReference('Page.RecentItem');
	        Test.setCurrentPage(pageRef);
	 
	         list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        delete filters;
	
	        test.startTest();
	
	                 account myaccount=new account(name='recent item test 764411');
		            insert myaccount;
		           String MytestrecordID=myaccount.id;
		            String MytestLink='https://ap1.salesforce.com/'+myaccount.id;
	                
	                RecentItem__c aRecord=new RecentItem__c(user__c=userinfo.getUserId(),recordid__c=MytestrecordID,link__c=MytestLink,object__c='Account', Record_Name__c='test record name');
	                insert aRecord;
	                
	                ApexPages.currentPage().getHeaders().put('Referer',MytestLink);
	                RecentItem controller = new RecentItem();
	
	                
	                controller.URL=MytestLink;
	                controller.GetRecentItem();
	                controller.getmyrecentitemsList();
	                controller.getRIList();
	                controller.getObjectNameList();
	           
	              test.stopTest();
	    }
	    
	static testMethod void TestRecentItemNewItem(){
	
	        
	         PageReference pageRef = new PageReference('Page.RecentItem');
	        Test.setCurrentPage(pageRef);
	       list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        delete filters;
	
	                test.startTest();
	                   account myaccount=new account(name='recent item test 764411');
				    insert myaccount;
				     String MytestrecordID=myaccount.id;
			            String MytestLink='https://ap1.salesforce.com/'+myaccount.id+'?retURL=123';
	                ApexPages.currentPage().getHeaders().put('Referer',MytestLink);
	                RecentItem controller = new RecentItem();
	                controller.URL=MytestLink;
	                controller.GetRecentItem();
	           
	              test.stopTest();
	    }
	    
	static testMethod void TestRecentItemCoverNoofAccess(){
	
	        
	         PageReference pageRef = new PageReference('Page.RecentItem');
	        Test.setCurrentPage(pageRef);
	       list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        delete filters;
	
	                test.startTest();
	                   account myaccount=new account(name='recent item test 764411');
					    insert myaccount;
					     String MytestrecordID=myaccount.id;
					            String MytestLink='https://ap1.salesforce.com/'+myaccount.id;
	                //cover No_Of_Access__c//
	                RecentItem__c aRecord=new RecentItem__c(No_Of_Access__c=1,user__c=userinfo.getUserId(),recordid__c=MytestrecordID,link__c=MytestLink,object__c='Account', Record_Name__c='test record name');
	                insert aRecord;
	                
	                ApexPages.currentPage().getHeaders().put('Referer',MytestLink);
	                RecentItem controller = new RecentItem();
	
	                
	                controller.URL=MytestLink;
	                controller.GetRecentItem();
	           
	              test.stopTest();
	    }
	    
	 static testMethod void CoverFilterBothObjectandNoDisplay(){
	
	        
	         PageReference pageRef = new PageReference('Page.RecentItem');
	        Test.setCurrentPage(pageRef);
	       list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        delete filters;
	
	                test.startTest();
	                   account myaccount=new account(name='recent item test 764411');
					    insert myaccount;
					     String MytestrecordID=myaccount.id;
					            String MytestLink='https://ap1.salesforce.com/'+myaccount.id;
	                RecentItemFilter__c aF=new RecentItemFilter__c(Objects_List__c='Account',No_Of_Displayed_Items__c=20);
	                insert af;
	                
	                //cover No_Of_Access__c//
	                RecentItem__c aRecord=new RecentItem__c(No_Of_Access__c=1,user__c=userinfo.getUserId(),recordid__c=MytestrecordID,link__c=MytestLink,object__c='Account', Record_Name__c='test record name');
	                insert aRecord;
	                
	                ApexPages.currentPage().getHeaders().put('Referer',MytestLink);
	                RecentItem controller = new RecentItem();
	
	                
	                controller.URL=MytestLink;
	                controller.GetRecentItem();
	           
	              test.stopTest();
	    }
	    
	           
     static testMethod void CoverFilterNoDisplay(){
    
            
             PageReference pageRef = new PageReference('Page.RecentItem');
            Test.setCurrentPage(pageRef);
           list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        delete filters;
                  
                  test.startTest();
                       account myaccount=new account(name='recent item test 764411');
					    insert myaccount;
					     String MytestrecordID=myaccount.id;
					            String MytestLink='https://ap1.salesforce.com/'+myaccount.id;
                    RecentItemFilter__c aF2=new RecentItemFilter__c(No_Of_Displayed_Items__c=20);
                    insert af2;
                    
                    //cover No_Of_Access__c//
                    RecentItem__c aRecord2=new RecentItem__c(No_Of_Access__c=1,user__c=userinfo.getUserId(),recordid__c=MytestrecordID,link__c=MytestLink,object__c='Account', Record_Name__c='test record name');
                    insert aRecord2;
                    
                    ApexPages.currentPage().getHeaders().put('Referer',MytestLink);
                    RecentItem controller2 = new RecentItem();
    
                    
                    controller2.URL=MytestLink;
                    controller2.GetRecentItem();
               
                  test.stopTest();
        }
        
    static testMethod void CoverNeitherFilter(){
    
            
             PageReference pageRef = new PageReference('Page.RecentItem');
            Test.setCurrentPage(pageRef);
            list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        delete filters;
                  
                  test.startTest();
                       account myaccount=new account(name='recent item test 764411');
				    insert myaccount;
				    String MytestrecordID=myaccount.id;
				            String MytestLink='https://ap1.salesforce.com/'+myaccount.id;
                    RecentItemFilter__c aF2=new RecentItemFilter__c();
                    insert af2;
                    
                    //cover No_Of_Access__c//
                    RecentItem__c aRecord2=new RecentItem__c(No_Of_Access__c=1,user__c=userinfo.getUserId(),recordid__c=MytestrecordID,link__c=MytestLink,object__c='Account', Record_Name__c='test record name');
                    insert aRecord2;
                    
                    ApexPages.currentPage().getHeaders().put('Referer',MytestLink);
                    RecentItem controller2 = new RecentItem();
    
                    
                    controller2.URL=MytestLink;
                    controller2.GetRecentItem();
               
                  test.stopTest();
        }
        
     static testMethod void CoverFilterObject(){
    
            
             PageReference pageRef = new PageReference('Page.RecentItem');
            Test.setCurrentPage(pageRef);
           
                  list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        delete filters;
                  test.startTest();
                       account myaccount=new account(name='recent item test 764411');
					    insert myaccount;
					     String MytestrecordID=myaccount.id;
					            String MytestLink='https://ap1.salesforce.com/'+myaccount.id;
                    RecentItemFilter__c aF2=new RecentItemFilter__c(Objects_List__c='Account');
                    insert af2;
                    
                    //cover No_Of_Access__c//
                    RecentItem__c aRecord2=new RecentItem__c(No_Of_Access__c=1,user__c=userinfo.getUserId(),recordid__c=MytestrecordID,link__c=MytestLink,object__c='Account', Record_Name__c='test record name');
                    insert aRecord2;
                    
                    ApexPages.currentPage().getHeaders().put('Referer',MytestLink);
                    RecentItem controller2 = new RecentItem();
    
                    
                    controller2.URL=MytestLink;
                    controller2.GetRecentItem();
               
                  test.stopTest();
        }
        
      static testMethod void Coveridea(){
    
            
             PageReference pageRef = new PageReference('Page.RecentItem');
            Test.setCurrentPage(pageRef);
                list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        delete filters;
                  
                  test.startTest();
                    
                    community c=[select id from community limit 1];
                  idea a=new idea(title='recent item idea test 764411',communityid=c.id);  
                    insert a;
                              String MytestrecordID=a.id;
           				 String MytestLink='https://ap1.salesforce.com/ideas/viewIdea.apexp?id='+a.id;
                    
                    //cover No_Of_Access__c//
                    RecentItem__c aRecord2=new RecentItem__c(No_Of_Access__c=1,user__c=userinfo.getUserId(),recordid__c=MytestrecordID,link__c=MytestLink,object__c='Idea', Record_Name__c='test record name');
                    insert aRecord2;
                    
                    ApexPages.currentPage().getHeaders().put('Referer',MytestLink);
                    RecentItem controller2 = new RecentItem();
    
                    
                    controller2.URL=MytestLink;
                    controller2.GetRecentItem();
               
                  test.stopTest();
        }
        
    static testMethod void CoverRecentItemandFilter(){
    
            
             PageReference pageRef = new PageReference('Page.RecentItem');
            Test.setCurrentPage(pageRef);
  				list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        delete filters;
                  
                  test.startTest();
                    
                  RecentItem__c a=new RecentItem__c(user__c=userinfo.getUserId(),recordid__c='123',link__c='123',object__c='RecentItem', Record_Name__c='123');
                    insert a;
                              String MytestLink='https://ap1.salesforce.com/'+a.id;
                    
                    ApexPages.currentPage().getHeaders().put('Referer',MytestLink);
                    RecentItem controller = new RecentItem();
                    controller.URL=MytestLink;
                    controller.GetRecentItem();
               
                  test.stopTest();
        }
        
    static testMethod void CoverNote(){
    
            
             PageReference pageRef = new PageReference('Page.RecentItem');
            Test.setCurrentPage(pageRef);
 				 list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        delete filters;
                  
                  test.startTest();
                    
                    account myaccount=new account(name='recent item test 764411');
            		insert myaccount;
                 note a=new note(parentid=myaccount.id,body='123',title='123');

                    insert a;
                              String MytestLink='https://ap1.salesforce.com/'+a.id;
                    
                    ApexPages.currentPage().getHeaders().put('Referer',MytestLink);
                    RecentItem controller = new RecentItem();
                    controller.URL=MytestLink;
                    controller.GetRecentItem();
               
                  test.stopTest();
        }
        
     static testMethod void CoverCase(){
    
            
             PageReference pageRef = new PageReference('Page.RecentItem');
            Test.setCurrentPage(pageRef);
  					list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        			delete filters;
                  
                  test.startTest();
                    
                    account myaccount=new account(name='recent item test 764411');
            		insert myaccount;
                 case a=new case(status='new',Origin='web' );

                    insert a;
                              String MytestLink='https://ap1.salesforce.com/'+a.id;
                    
                    ApexPages.currentPage().getHeaders().put('Referer',MytestLink);
                    RecentItem controller = new RecentItem();
                    controller.URL=MytestLink;
                    controller.GetRecentItem();
               
                  test.stopTest();
        }
        
    static testMethod void Coversolution(){
    
            
             PageReference pageRef = new PageReference('Page.RecentItem');
            Test.setCurrentPage(pageRef);
  				list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        		delete filters;
                  
                  test.startTest();

                 solution a=new solution(SolutionName='123');

                    insert a;
                              String MytestLink='https://ap1.salesforce.com/'+a.id;
                    
                    ApexPages.currentPage().getHeaders().put('Referer',MytestLink);
                    RecentItem controller = new RecentItem();
                    controller.URL=MytestLink;
                    controller.GetRecentItem();
               
                  test.stopTest();
        }
        
    static testMethod void CoverContract(){
    
            
             PageReference pageRef = new PageReference('Page.RecentItem');
            Test.setCurrentPage(pageRef);
  			list<RecentItemFilter__c> filters=[select id from RecentItemFilter__c];
	        delete filters;
                  
                  test.startTest();
				 account myaccount=new account(name='recent item test 764411');
				            insert myaccount;
                 Contract a=new Contract(StartDate=date.today(), ContractTerm=10, AccountId=myaccount.id);

                    insert a;
                              String MytestLink='https://ap1.salesforce.com/'+a.id;
                    
                    ApexPages.currentPage().getHeaders().put('Referer',MytestLink);
                    RecentItem controller = new RecentItem();
                    controller.URL=MytestLink;
                    controller.GetRecentItem();
               
                  test.stopTest();
        }
}